### ISSUE TITLE
Extensible services?

### ISSUE THREAD

**Issue by luxaritas** [ElementalAlchemist/txircd#150]
The use of txircd in [the project I'm working on](https://github.com/EteRNAgame/HTML-Chat/) will require some unorthodox methods of authentication. Is/can services be built in such a way that it can be extended to allow for things like additional authentication systems (in my case, some form of SSO with the site the client is embedded on, possibly through ZNC as I'm currently looking at that)? Similarly, we also allow multiple clients connected by one user, using a ^# to differentiate nicks, so it would need to work in such a way that multiple nicks could be accepted in an SSO situation (again, unless we start using ZNC).

Ideally services could also do things like automatically giving users perfixes, is this possible?

**Comment by ElementalAlchemist** [comment]
I'm currently planning to make a generic services that will be extensible in this sort of way, yes. I'm trying to get txircd to go back to being used for a different project which will also require custom authentication to work (email/password, but if you don't mind writing a module to hook up your services stuff to your thing, it should be possible).

I'll keep this open for now as services are very, very WIP (read: barely started).

**Comment by ElementalAlchemist** [comment]
This should be fixed in the current beta branch, which I'm now moving to stable aggressively. You should be able to do something similar to what's in the modules/extra/services/desertbus directory to connect things to whatever service you're using.

If you don't think those will work for what you're trying to do, feel free to reopen.
